src/Entity/Message.php
<?php

namespace App\Entity;

use App\Repository\MessageRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: MessageRepository::class)]
class Message
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column(type: 'integer')]
    private $id;

    #[ORM\Column(type: 'text')]
    private $created_at;

    #[ORM\Column(type: 'text')]
    private $content;

    #[ORM\ManyToOne(targetEntity: UserAuth::class, inversedBy: 'messages')]
    private $user;

    #[ORM\OneToMany(mappedBy: 'message', targetEntity: Files::class, cascade: ['persist', 'remove'])]
    private $files;

    #[ORM\ManyToOne(targetEntity: Subject::class, inversedBy: 'messages')]
    #[ORM\JoinColumn(nullable: false)]
    private $subject;

    public function __construct()
    {
        $this->files = new ArrayCollection();
    }

    public function getUploadUrl(): ?string
    {
        return "http://" . $_SERVER['HTTP_HOST'] . "/uploads/";
    }    
    
    public function getId(): ?int
    {
        return $this->id;
    }

    public function getCreatedAt(): ?string
    {
        return $this->created_at;
    }

    public function setCreatedAt(string $created_at): self
    {
        $this->created_at = $created_at;

        return $this;
    }

    public function getContent(): ?string
    {
        return $this->content;
    }

    public function setContent(string $content): self
    {
        $this->content = $content;

        return $this;
    }

    public function getUser(): ?UserAuth
    {
        return $this->user;
    }

    public function setUser(?UserAuth $user): self
    {
        $this->user = $user;

        return $this;
    }

    /**
     * @return Collection<int, Files>
     */
    public function getFiles(): Collection
    {
        return $this->files;
    }

    public function addFile(Files $file): self
    {
        if (!$this->files->contains($file)) {
            $this->files[] = $file;
            $file->setMessage($this);
        }

        return $this;
    }

    public function removeFile(Files $file): self
    {
        if ($this->files->removeElement($file)) {
            // set the owning side to null (unless already changed)
            if ($file->getMessage() === $this) {
                $file->setMessage(null);
            }
        }

        return $this;
    }

    public function getSubject(): ?Subject
    {
        return $this->subject;
    }

    public function setSubject(?Subject $subject): self
    {
        $this->subject = $subject;

        return $this;
    }
}

src/Form/MessageType.php
<?php

namespace App\Form;

use App\Entity\Message;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;
use Symfony\Component\Form\Extension\Core\Type\FileType;
use Symfony\Component\Validator\Constraints\File;

class MessageType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            ->add('created_at')
            ->add('content')
            ->add('subject')
            ->add('files', FileType::class, [
              'mapped' => false,
              'label' => 'Files',
              'required' => false,
              'constraints' => [
                  new File([
                      'maxSize' => '2M'
                      ])
                  ]
              ])
            // ->add('user')
        ;
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => Message::class,
        ]);
    }
}

src/Controller/MessageController.php
<?php

namespace App\Controller;

use App\Entity\Message;
use App\Entity\Subject;
use App\Entity\Files;
use App\Form\MessageType;
use App\Repository\MessageRepository;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

#[Route('/message')]
class MessageController extends AbstractController
{
    #[Route('/', name: 'app_message_index', methods: ['GET'])]
    public function index(EntityManagerInterface $entityManager): Response
    {
        $this->denyAccessUnlessGranted('ROLE_ADMIN');
        $messages = $entityManager
            ->getRepository(Message::class)
            ->findAll();
        $uploadsDir = "/uploads/";
        
        return $this->render('message/index.html.twig', [
            'messages' => $messages,
            'uploadsDir' => "http://" . $_SERVER['HTTP_HOST'] . $uploadsDir,
        ]);
    }

    #[Route('/{id}/new', name: 'app_message_new', methods: ['GET', 'POST'])]
    public function new(Subject $subjectId, Request $request, EntityManagerInterface $entityManager): Response
    {
        $message = new Message();

        if ($request->request->get('content') != null) {
          if($this->IsGranted('ROLE_USER')) {
            // Get current user
            $user = $this->getUser();
            $message->setUser($user);
            $message->setSubject($subjectId);
            $content = $request->request->get('content');
            $message->setContent($content);
            // get files inside request
            if ($message->getCreatedAt() === null) {
              $currentDate = new \DateTime('now');
              $message->setCreatedAt($currentDate->format('Y-m-d H:i:s'));
            }
            if($request->files->get('files') != null) {
              $filesRequest = $request->files->get('files');
              $uploadsDir = $this->getParameter('app.uploads_dir');
              // set uploads dir
              // Set the title of the file
              foreach($filesRequest as $key => $file) {
                $fileName = time() . "." . $file->guessExtension();
                $files = new Files();
                // Set the title of the file
                $files->setName($fileName);
                // Need to persist files before continue
                $entityManager->persist($files);
                // Add the file to message
                $message->addFile($files);
                $file->move($uploadsDir, $fileName);
              }
            }
          }else {
            throw new Exception('Access Denied.');
          }
          $entityManager->persist($message);
          $entityManager->flush();
          return $this->redirectToRoute('app_subject_show', ['id' => $subjectId->getId(), 'message' => $message->getId()], Response::HTTP_SEE_OTHER);
        }
        return $this->redirectToRoute('app_subject_show', ['id' => $subjectId->getId()], Response::HTTP_SEE_OTHER);
    }

    #[Route('/{id}', name: 'app_message_show', methods: ['GET'])]
    public function show(Message $message): Response
    {
        return $this->render('message/show.html.twig', [
            'message' => $message,
        ]);
    }

    #[Route('/{id}/edit', name: 'app_message_edit', methods: ['GET', 'POST'])]
    public function edit(Request $request, Message $message, EntityManagerInterface $entityManager): Response
    {
        $form = $this->createForm(MessageType::class, $message);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager->flush();

            return $this->redirectToRoute('app_message_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->renderForm('message/edit.html.twig', [
            'message' => $message,
            'form' => $form,
        ]);
    }

    #[Route('/delete/{id}', name: 'app_message_delete', methods: ['POST'])]
    public function delete(Request $request, Message $message, EntityManagerInterface $entityManager): Response
    {
      if($this->IsGranted('ROLE_ADMIN')) {
        if ($this->isCsrfTokenValid('delete'.$message->getId(), $request->request->get('_token'))) {
            $entityManager->remove($message);
            $entityManager->flush();
        }
      }else {
          throw new Exception('Access Denied.');
        }

        return $this->redirectToRoute('app_message_index', [], Response::HTTP_SEE_OTHER);
    }
}

templates/message/_delete_form.html.twig
<form method="post" action="{{ path('app_message_delete', {'id': message.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ message.id) }}">
    <button class="btn">Delete</button>
</form>

templates/message/_form.html.twig
{{ form_start(form) }}
    {{ form_widget(form) }}
    <button class="btn">{{ button_label|default('Save') }}</button>
{{ form_end(form) }}

templates/message/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Edit Message{% endblock %}

{% block body %}
    <h1>Edit Message</h1>

    {{ include('message/_form.html.twig', {'button_label': 'Update'}) }}

    <a href="{{ path('app_message_index') }}">back to list</a>

    {{ include('message/_delete_form.html.twig') }}
{% endblock %}

templates/message/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Message index{% endblock %}

{% block body %}
    <h1>Message index</h1>

    <table class="table">
        <thead>
            <tr>
                <th>Id</th>
                <th>Created_at</th>
                <th>Content</th>
                <th>Files</th>
                <th>Create by</th>
                <th>actions</th>
            </tr>
        </thead>
        <tbody>
        {% for message in messages %}
            <tr>
                <td>{{ message.id }}</td>
                <td>{{ message.createdAt ? message.createdAt|date('Y-m-d') : '' }}</td>
                <td>{{ message.content|u.truncate(20, "...") }}</td>
                <td>{% for file in message.files %}
                  <img class="file" src="{{ uploadsDir }}{{ file.name }}">
                {% endfor %}
                </td>
                <td>{{ message.user }}</td>
                <td>
                    <a href="{{ path('app_message_show', {'id': message.id}) }}">show</a>
                    <a href="{{ path('app_message_edit', {'id': message.id}) }}">edit</a>
                </td>
            </tr>
        {% else %}
            <tr>
                <td colspan="4">no records found</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>

    {# <a href="{{ path('app_message_new') }}">Create new</a> #}
{% endblock %}

templates/message/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}New Message{% endblock %}

{% block body %}
    <h1>Create new Message</h1>

    {{ include('message/_form.html.twig') }}

    <a href="{{ path('app_message_index') }}">back to list</a>
{% endblock %}

templates/message/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}Message{% endblock %}

{% block body %}
    <h1>Message</h1>

    <table class="table">
        <tbody>
            <tr>
                <th>Id</th>
                <td>{{ message.id }}</td>
            </tr>
            <tr>
                <th>Created_at</th>
                <td>{{ message.createdAt ? message.createdAt|date('Y-m-d') : '' }}</td>
            </tr>
            <tr>
                <th>Content</th>
                <td>{{ message.content }}</td>
            </tr>
        </tbody>
    </table>

    <a href="{{ path('app_message_index') }}">back to list</a>

    <a href="{{ path('app_message_edit', {'id': message.id}) }}">edit</a>

    {{ include('message/_delete_form.html.twig') }}
{% endblock %}